# Generated by Django 2.2.7 on 2019-11-09 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Twitter',
            new_name='Tweet',
        ),
    ]
